'use strict';
/* ════════════════════════════════════════════════════════════
   MATERIDEX · DATA MODEL
   All property values are REPRESENTATIVE LITERATURE RANGES unless
   flagged. kind: 'lit' literature range · 'calc' calculated estimate
   · 'game' gameplay abstraction. Rarity = discovery significance in
   the Codex, NOT real-world abundance.
   ════════════════════════════════════════════════════════════ */
const BRAND = { name:'MATERIDEX', sub:'MATERIALS CODEX' };

const FAMILIES = {
  carbon:      {name:'Carbon Forms',        color:'#cdbcf7', region:'composite'},
  twoD:        {name:'2D Materials',        color:'#a78bfa', region:'nexus'},
  metal:       {name:'Metals & Alloys',     color:'#ff8a5c', region:'foundry'},
  ceramic:     {name:'Ceramics & Glasses',  color:'#e9e3d5', region:'ceramic'},
  polymer:     {name:'Polymers',            color:'#8fd8a8', region:'polymer'},
  semi:        {name:'Semiconductors',      color:'#8fd8f2', region:'nexus'},
  smart:       {name:'Smart Materials',     color:'#f0a8f8', region:'foundry'},
  energy:      {name:'Energy Crystals',     color:'#d8c8a4', region:'nexus'},
  composite:   {name:'Composites',          color:'#b8a8e8', region:'composite'},
  bio:         {name:'Nano Biostructures',  color:'#7fe8c8', region:'bio'},
};
const REGIONS = {
  foundry:  {name:'Metals Foundry',       color:'#ff8a5c', blurb:'A molten cathedral of alloys — phase transformations, furnaces and crystalline grains.', hazards:['Extreme Heat','Molten Flow'], env:'A cathedral of crucibles where grain boundaries glow like stained glass.'},
  ceramic:  {name:'Ceramic Wilds',        color:'#e9e3d5', blurb:'A pale cracked moon of glass forests, refractory cliffs and translucent crystal caves.', hazards:['Brittle Fracture','Thermal Shock'], env:'Silence, whiteness, and cliffs that ring when struck.'},
  polymer:  {name:'Polymer Canopy',       color:'#8fd8a8', blurb:'A responsive bioluminescent forest where chains stretch, entangle and crosslink.', hazards:['UV Degradation','Creep'], env:'The canopy breathes; every vine is a macromolecule.'},
  nexus:    {name:'Semiconductor Nexus',  color:'#8fd8f2', blurb:'A crystalline city where charge flows like water and band structures form towering spires.', hazards:['High Radiation','Thermal Flux','Quantum Instability'], env:'Electrons flow like light through lattices of impossible precision.'},
  composite:{name:'Composite Frontier',   color:'#b8a8e8', blurb:'A folded landscape of fibres, matrices, laminates and hierarchical interfaces.', hazards:['Delamination','Galvanic Zones'], env:'Terrain woven layer upon layer, strong along one heading only.'},
  bio:      {name:'Biofabricated Depths', color:'#7fe8c8', blurb:'A living reef of hydrogels, cellulose, mycelium, collagen and regenerative matter.', hazards:['Enzymatic Decay','Hydration Swings'], env:'The reef grows back whatever you take — differently.'},
};

/* radar axes: strength, conductivity, flexibility, stability, sustainability, affordability (all 0-10, kind:'game') */
function M(o){ return Object.assign({
  discovered:false, masteryXP:0, dupes:0, fav:false,
  refs:[], lore:'', limitations:[], synth:[], apps:[], tags:[], related:[],
  sim:null, load:null, specimen:'crystal',
}, o); }

const MATERIALS = {

graphene: M({ id:'graphene', code:'MAT-006', name:'Graphene', formula:'C (sp²)', family:'twoD', cls:'2D carbon allotrope',
  rarity:'legendary', region:'nexus', color:'#cdbcf7', specimen:'veil',
  summary:'An atomically thin sheet of sp²-bonded carbon arranged in a hexagonal lattice. Extraordinary strength, conductivity, and potential.',
  desc:'Graphene is a single layer of carbon atoms in a honeycomb lattice — the first two-dimensional material isolated in the laboratory (Novoselov & Geim, 2004, by mechanical exfoliation of graphite). Each carbon bonds to three neighbours through sp² hybridisation; the remaining π-electrons delocalise across the plane, giving exceptional in-plane electrical and thermal transport. Pristine monolayer graphene is the strongest material ever tensile-tested, yet real sheets are governed by their defects: vacancies, Stone–Wales rotations and grain boundaries decide where they tear.',
  bonding:{hybrid:'sp² hybridisation', structure:'Honeycomb lattice (2D hexagonal)', note:'σ-bonds in plane (~0.142 nm C–C), delocalised π-system above and below the sheet.'},
  props:[
    {k:'Tensile strength', v:'~130', range:'100–130', u:'GPa', kind:'lit', note:'defect-free monolayer, AFM nanoindentation (Lee et al. 2008); CVD films with grain boundaries measure far lower', icon:'str'},
    {k:'Young’s modulus', v:'~1', range:'0.8–1.1', u:'TPa', kind:'lit', icon:'str'},
    {k:'Electrical conductivity', v:'~10⁷', range:'10⁶–10⁸', u:'S/m', kind:'lit', note:'sheet-equivalent; depends on substrate, doping and defects', icon:'ele'},
    {k:'Density', v:'2.26', u:'g/cm³', kind:'lit', note:'graphite-equivalent bulk value', icon:'den'},
    {k:'Thermal conductivity', v:'2000–5300', u:'W/m·K', kind:'lit', note:'suspended monolayer, room temperature', icon:'thm'},
    {k:'Failure strain', v:'~25', range:'13–25', u:'%', kind:'lit', icon:'str'},
    {k:'Optical absorption', v:'2.3', u:'% per layer', kind:'lit', icon:'opt'},
  ],
  radar:{strength:10, conductivity:9.5, flexibility:9, stability:7.5, sustainability:6, affordability:2.5},
  apps:['Aerospace','Flexible Electronics','Energy Storage','Sensors','Composites','Membranes'],
  synth:[{n:'Chemical Vapour Deposition (CVD)', d:'Methane decomposed over copper foil ~1000 °C; large-area polycrystalline films.'},
         {n:'Mechanical exfoliation', d:'The original “sticky tape” route; highest quality, microscopic flakes.'},
         {n:'Liquid-phase exfoliation', d:'Graphite sheared in solvent; bulk dispersions for inks and composites.'},
         {n:'Reduction of graphene oxide', d:'Cheap and scalable, but defect-rich lattices.'}],
  limitations:['Zero intrinsic bandgap limits digital transistor use','Properties collapse with defects and grain boundaries','Large-area transfer without damage remains difficult','Costly at electronic-grade quality'],
  lore:'The Miracle Material. First lifted from graphite with adhesive tape — a Nobel-winning experiment cheap enough for a school lab, describing a lattice strong enough to hold a cat and light enough that the cat’s whisker would outweigh the sheet.',
  related:['cnt','diamond','mxene','pedot'],
  tags:['conductive','flexible','strong','light','transparent','2d','carbon','wearable','electrode','thermal'],
  refs:['Novoselov, Geim et al., Science 306, 666 (2004)','Lee, Wei, Kysar & Hone, Science 321, 385 (2008)','Balandin et al., Nano Lett. 8, 902 (2008)','Nair et al., Science 320, 1308 (2008)'],
  sim:{E:1000, uts:130, failStrain:0.25, ductile:false, conduct:true},
  load:{rho:2260, sigma:130000, E:1000, tmin:-269, tmax:400, cost:'>100', costkg:2000, co2:60, fatigue:4, repair:1, corr:5, manu:1.5, recy:2} }),

cnt: M({ id:'cnt', code:'MAT-017', name:'Carbon Nanotube', formula:'C (sp²)', family:'carbon', cls:'1D carbon allotrope',
  rarity:'epic', region:'composite', color:'#a99df0', specimen:'tube',
  summary:'Graphene rolled into a seamless cylinder — nature’s strongest known fibre geometry.',
  desc:'Single- and multi-walled nanotubes carry graphene’s bonding into one dimension. Chirality — the roll angle — decides whether a tube behaves as a metal or a semiconductor, a property no bulk material shares.',
  bonding:{hybrid:'sp²', structure:'Rolled honeycomb cylinder', note:'Chirality (n,m) sets metallic vs semiconducting behaviour.'},
  props:[
    {k:'Tensile strength', v:'11–63', u:'GPa', kind:'lit', note:'individual MWCNT measurements', icon:'str'},
    {k:'Young’s modulus', v:'~1', u:'TPa', kind:'lit', icon:'str'},
    {k:'Density', v:'1.3–1.4', u:'g/cm³', kind:'lit', icon:'den'},
    {k:'Thermal conductivity', v:'~3000', u:'W/m·K', kind:'lit', note:'axial, individual tube', icon:'thm'},
  ],
  radar:{strength:9.5, conductivity:8.5, flexibility:8.5, stability:7.5, sustainability:5, affordability:3},
  apps:['Composites','Conductive Inks','Field Emission','Sensors','Energy Storage'],
  synth:[{n:'CVD on catalyst particles', d:'Workhorse route; forests and powders.'},{n:'Arc discharge', d:'High crystallinity, low yield.'}],
  limitations:['Bulk assemblies never reach single-tube properties','Chirality control at scale unsolved','Dispersion and alignment dominate composite performance'],
  lore:'A material that chooses its own electronic destiny by the angle at which it was rolled.',
  related:['graphene','cfrp','diamond'], tags:['strong','conductive','light','fibre','carbon','composite'],
  refs:['Iijima, Nature 354, 56 (1991)','Yu et al., Science 287, 637 (2000)'],
  sim:{E:1000, uts:60, failStrain:0.12, ductile:false, conduct:true},
  load:{rho:1350, sigma:30000, E:1000, tmin:-269, tmax:450, costkg:500, co2:45, fatigue:4, repair:1, corr:5, manu:2, recy:2} }),

diamond: M({ id:'diamond', code:'MAT-002', name:'Diamond', formula:'C (sp³)', family:'carbon', cls:'3D carbon allotrope',
  rarity:'epic', region:'ceramic', color:'#e8f4ff', specimen:'gem',
  summary:'Carbon’s tetrahedral fortress — the hardest natural material and a superb thermal conductor.',
  desc:'Every carbon bonds to four neighbours in a rigid tetrahedral network. The result: extreme hardness, the highest thermal conductivity of any bulk solid, wide-bandgap transparency — and total electrical insulation unless doped.',
  bonding:{hybrid:'sp³', structure:'Diamond cubic lattice', note:'Tetrahedral network; no free π-electrons.'},
  props:[
    {k:'Hardness', v:'~10', u:'Mohs / ~90 GPa Vickers', kind:'lit', icon:'str'},
    {k:'Thermal conductivity', v:'~2200', u:'W/m·K', kind:'lit', icon:'thm'},
    {k:'Bandgap', v:'5.47', u:'eV', kind:'lit', icon:'ele'},
    {k:'Density', v:'3.51', u:'g/cm³', kind:'lit', icon:'den'},
  ],
  radar:{strength:9.5, conductivity:1, flexibility:1, stability:9, sustainability:4, affordability:2},
  apps:['Cutting Tools','Heat Spreaders','Optics','Quantum Sensing','Anvils'],
  synth:[{n:'HPHT', d:'High pressure, high temperature — mimics the mantle.'},{n:'CVD', d:'Plasma growth atom by atom; electronic-grade single crystal.'}],
  limitations:['Brittle despite hardness','Burns in oxygen above ~700 °C','Costly in large single crystals'],
  lore:'The same atom as soot, arranged with different conviction.',
  related:['graphene','sic','cnt'], tags:['hard','thermal','optical','insulator','carbon'],
  refs:['Field, The Properties of Natural and Synthetic Diamond (1992)'],
  sim:{E:1100, uts:95, failStrain:0.08, ductile:false, conduct:false},
  load:{rho:3510, sigma:2800, E:1100, tmin:-269, tmax:700, costkg:100000, co2:100, fatigue:3, repair:0, corr:5, manu:1, recy:1} }),

aerogel: M({ id:'aerogel', code:'MAT-018', name:'Silica Aerogel', formula:'SiO₂ (porous)', family:'ceramic', cls:'Ultra-porous ceramic',
  rarity:'rare', region:'ceramic', color:'#bcd8f0', specimen:'smoke',
  summary:'Frozen smoke. A solid that is ~99% air, and one of the best thermal insulators known.',
  desc:'A silica gel whose liquid was replaced by gas without collapsing the nanoscale skeleton (supercritical drying). Nanopores smaller than air’s mean free path suppress convection and conduction — hence the extraordinary insulation. NASA flew it to catch comet dust intact.',
  bonding:{hybrid:'Si–O network', structure:'Fractal nanoporous network', note:'~95–99.8% porosity; pearl-necklace silica strands.'},
  props:[
    {k:'Density', v:'0.003–0.35', u:'g/cm³', kind:'lit', note:'record holders near 1 kg/m³', icon:'den'},
    {k:'Thermal conductivity', v:'0.013–0.02', u:'W/m·K', kind:'lit', note:'better than still air', icon:'thm'},
    {k:'Porosity', v:'95–99.8', u:'%', kind:'lit', icon:'den'},
    {k:'Compressive strength', v:'0.1–2', u:'MPa', kind:'lit', icon:'str'},
  ],
  radar:{strength:1.5, conductivity:.5, flexibility:2, stability:6.5, sustainability:6, affordability:4},
  apps:['Thermal Insulation','Particle Capture','Aerospace','Cherenkov Detectors'],
  synth:[{n:'Sol-gel + supercritical CO₂ drying', d:'Avoids capillary collapse of the skeleton.'}],
  limitations:['Fragile and dusty in monolithic form','Hydrophilic unless treated','Slow, costly drying step'],
  lore:'Recovered from a cryo-sealed research drone lost in the upper atmosphere. Its structure is 99.8% air, yet it defies gravity and time. Holding it feels like holding a secret.',
  related:['glass','cellulose','hydrogel'], tags:['insulation','light','porous','thermal','aerospace'],
  refs:['Kistler, Nature 127, 741 (1931)','NASA Stardust mission documentation'],
  sim:{E:0.005, uts:0.001, failStrain:0.04, ductile:false, conduct:false},
  load:{rho:100, sigma:1, E:0.005, tmin:-269, tmax:600, costkg:300, co2:8, fatigue:1, repair:0, corr:4, manu:2, recy:2} }),

mxene: M({ id:'mxene', code:'MAT-041', name:'MXene (Ti₃C₂Tₓ)', formula:'Ti₃C₂Tₓ', family:'twoD', cls:'2D transition-metal carbide',
  rarity:'epic', region:'nexus', color:'#9fb8f8', specimen:'layers',
  summary:'A family of 2D transition-metal carbides and nitrides with metal-grade conductivity and clay-like processability.',
  desc:'Made by etching the A-layer out of layered MAX phases (first at Drexel, 2011). Hydrophilic surface terminations (–O, –OH, –F) make MXenes water-processable while staying metallically conductive — a rare combination that suits printed electronics, EMI shielding and supercapacitors.',
  bonding:{hybrid:'Metallic + ionic', structure:'Layered 2D carbide sheets', note:'Surface terminations Tₓ tune work function and chemistry.'},
  props:[
    {k:'Electrical conductivity', v:'~10⁴–10⁶', u:'S/m', kind:'lit', note:'film quality dependent; record films ~2×10⁶', icon:'ele'},
    {k:'Young’s modulus', v:'~330', u:'GPa', kind:'lit', note:'monolayer Ti₃C₂Tₓ', icon:'str'},
    {k:'Density', v:'~3.7', u:'g/cm³', kind:'calc', icon:'den'},
  ],
  radar:{strength:7, conductivity:8.7, flexibility:8.9, stability:5.5, sustainability:4.5, affordability:3.5},
  apps:['EMI Shielding','Supercapacitors','Wearable Tech','Printed Antennas','Water Purification'],
  synth:[{n:'Selective etching of MAX phase', d:'HF or in-situ HF removes Al layers; delaminate to single flakes.'}],
  limitations:['Oxidises in humid air unless protected','HF-based etching is hazardous','Long-term stability still under study'],
  lore:'A metal that pours like ink.',
  related:['graphene','pedot','ti64'], tags:['conductive','flexible','2d','wearable','shielding','ink'],
  refs:['Naguib et al., Adv. Mater. 23, 4248 (2011)','Anasori & Gogotsi, 2D Metal Carbides and Nitrides (2019)'],
  sim:{E:330, uts:17, failStrain:0.03, ductile:false, conduct:true},
  load:{rho:3700, sigma:600, E:330, tmin:-100, tmax:300, costkg:800, co2:50, fatigue:2, repair:1, corr:2, manu:2, recy:2} }),

pedot: M({ id:'pedot', code:'MAT-082', name:'PEDOT:PSS', formula:'(C₆H₄O₂S)ₙ·PSS', family:'polymer', cls:'Conducting polymer',
  rarity:'epic', region:'polymer', color:'#8fd8c8', specimen:'web',
  summary:'The workhorse conducting polymer — transparent, flexible, water-processable.',
  desc:'A polythiophene derivative stabilised by polystyrene sulfonate. Spin-coat it from water into transparent conductive films; secondary dopants like DMSO push conductivity past 1000 S/cm. The standard hole-transport layer of organic electronics and the favourite electrode of e-textiles.',
  bonding:{hybrid:'Conjugated π backbone', structure:'Polymer blend, phase-separated grains', note:'Conductivity rises sharply with secondary doping.'},
  props:[
    {k:'Electrical conductivity', v:'10⁻¹–10³', u:'S/cm', kind:'lit', note:'formulation dependent', icon:'ele'},
    {k:'Transparency', v:'>85', u:'% (thin film, visible)', kind:'lit', icon:'opt'},
    {k:'Young’s modulus', v:'1–3', u:'GPa', kind:'lit', icon:'str'},
  ],
  radar:{strength:2.5, conductivity:6.5, flexibility:9.5, stability:4.5, sustainability:6, affordability:7},
  apps:['Wearable Tech','OLED Layers','Antistatic Coatings','Bioelectrodes','E-textiles'],
  synth:[{n:'Oxidative polymerisation', d:'Aqueous dispersion; coatable by spin, spray, inkjet.'}],
  limitations:['Conductivity far below metals','Hygroscopic; sensitive to humidity','Acidic PSS can corrode neighbours'],
  lore:'Plastic that learned to carry current — politely.',
  related:['graphene','mxene','silicone'], tags:['conductive','flexible','transparent','wearable','polymer','electrode','biocompatible'],
  refs:['Groenendaal et al., Adv. Mater. 12, 481 (2000)'],
  sim:{E:2, uts:0.05, failStrain:0.1, ductile:true, conduct:true},
  load:{rho:1100, sigma:45, E:2, tmin:-40, tmax:150, costkg:400, co2:12, fatigue:2, repair:2, corr:3, manu:4, recy:2} }),

liquidmetal: M({ id:'liquidmetal', code:'MAT-033', name:'Liquid Metal (EGaIn)', formula:'Ga–In eutectic', family:'smart', cls:'Room-temperature liquid alloy',
  rarity:'epic', region:'foundry', color:'#c8ccd8', specimen:'blob',
  summary:'A metal that flows at room temperature — stretchable circuits and self-healing conductors.',
  desc:'Eutectic gallium–indium melts below 16 °C. A nanometric oxide skin lets it hold shapes no liquid should, while staying conductive at any strain when encapsulated in elastomer channels — the backbone of stretchable electronics.',
  bonding:{hybrid:'Metallic (liquid)', structure:'Disordered liquid + Ga₂O₃ skin', note:'The oxide skin gives paradoxical shape retention.'},
  props:[
    {k:'Melting point', v:'15.5', u:'°C', kind:'lit', icon:'thm'},
    {k:'Electrical conductivity', v:'~3.4×10⁶', u:'S/m', kind:'lit', icon:'ele'},
    {k:'Density', v:'6.25', u:'g/cm³', kind:'lit', icon:'den'},
  ],
  radar:{strength:.5, conductivity:8, flexibility:10, stability:5, sustainability:4, affordability:4},
  apps:['Stretchable Circuits','Soft Robotics','Thermal Interfaces','Reconfigurable Antennas'],
  synth:[{n:'Alloying', d:'75.5% Ga, 24.5% In by weight.'}],
  limitations:['Embrittles aluminium aggressively','Gallium is a by-product metal — supply-limited','Needs encapsulation'],
  lore:'A responsive silver organism. It remembers the shape of every channel it has ever filled.',
  related:['nitinol','pedot','mxene'], tags:['conductive','stretchable','liquid','soft','wearable','selfhealing'],
  refs:['Dickey et al., Adv. Funct. Mater. 18, 1097 (2008)'],
  sim:{E:0.001, uts:0.0005, failStrain:3, ductile:true, conduct:true},
  load:{rho:6250, sigma:0.1, E:0.001, tmin:15, tmax:1300, costkg:600, co2:30, fatigue:5, repair:5, corr:2, manu:3, recy:4} }),

silicon: M({ id:'silicon', code:'MAT-014', name:'Silicon', formula:'Si', family:'semi', cls:'Elemental semiconductor',
  rarity:'rare', region:'nexus', color:'#9ab0c8', specimen:'ingot',
  summary:'The bedrock of the information age — a semiconductor grown as flawless single crystals metres long.',
  desc:'Diamond-cubic silicon, purified to eleven nines and pulled from the melt by the Czochralski process, is the most perfect crystalline object humans manufacture at scale. Its 1.12 eV bandgap and its stable native oxide made planar electronics possible.',
  bonding:{hybrid:'sp³ covalent', structure:'Diamond cubic', note:'Native SiO₂ passivation enabled the MOSFET.'},
  props:[
    {k:'Bandgap', v:'1.12', u:'eV (300 K, indirect)', kind:'lit', icon:'ele'},
    {k:'Density', v:'2.33', u:'g/cm³', kind:'lit', icon:'den'},
    {k:'Young’s modulus', v:'130–188', u:'GPa (orientation dep.)', kind:'lit', icon:'str'},
    {k:'Melting point', v:'1414', u:'°C', kind:'lit', icon:'thm'},
  ],
  radar:{strength:5.5, conductivity:5, flexibility:1.5, stability:8.5, sustainability:6, affordability:7},
  apps:['Microelectronics','Photovoltaics','MEMS','Photonics'],
  synth:[{n:'Czochralski growth', d:'Single crystal pulled from 1414 °C melt.'},{n:'Float-zone', d:'Ultra-high purity by travelling melt zone.'}],
  limitations:['Indirect bandgap — poor light emitter','Brittle wafers','Performance ceiling near ~150 °C junctions'],
  lore:'Beach sand, promoted to the substrate of civilisation.',
  related:['gaas','sic','perovskite'], tags:['semiconductor','electronic','solar','wafer'],
  refs:['Sze & Ng, Physics of Semiconductor Devices (2006)'],
  sim:{E:160, uts:7, failStrain:0.02, ductile:false, conduct:false},
  load:{rho:2330, sigma:120, E:160, tmin:-269, tmax:600, costkg:50, co2:20, fatigue:2, repair:0, corr:4, manu:3, recy:3} }),

gaas: M({ id:'gaas', code:'MAT-052', name:'Gallium Arsenide', formula:'GaAs', family:'semi', cls:'III-V compound semiconductor',
  rarity:'rare', region:'nexus', color:'#b89ad8', specimen:'ingot',
  summary:'Silicon’s faster cousin — direct bandgap, high electron mobility, born for lasers and radio.',
  desc:'A zinc-blende III-V crystal whose direct 1.42 eV gap emits light efficiently and whose electrons travel ~6× faster than in silicon — the choice for laser diodes, satellite solar cells and microwave amplifiers.',
  bonding:{hybrid:'Covalent (partial ionic)', structure:'Zinc blende', note:'Direct gap → efficient photon emission.'},
  props:[
    {k:'Bandgap', v:'1.42', u:'eV (300 K, direct)', kind:'lit', icon:'ele'},
    {k:'Electron mobility', v:'~8500', u:'cm²/V·s', kind:'lit', icon:'ele'},
    {k:'Density', v:'5.32', u:'g/cm³', kind:'lit', icon:'den'},
  ],
  radar:{strength:4, conductivity:6.5, flexibility:1, stability:7, sustainability:3, affordability:3},
  apps:['Laser Diodes','Space Photovoltaics','RF Amplifiers','LEDs'],
  synth:[{n:'LEC / VGF growth', d:'Bulk crystals under boric oxide encapsulant.'},{n:'MBE / MOCVD', d:'Atomically precise epitaxial layers.'}],
  limitations:['Arsenic toxicity in processing','Fragile wafers','Far costlier than silicon'],
  lore:'Where the Nexus keeps its light.',
  related:['silicon','perovskite'], tags:['semiconductor','laser','solar','rf','photonics'],
  refs:['Blakemore, J. Appl. Phys. 53, R123 (1982)'],
  sim:{E:86, uts:5, failStrain:0.015, ductile:false, conduct:false},
  load:{rho:5320, sigma:60, E:86, tmin:-269, tmax:450, costkg:900, co2:80, fatigue:2, repair:0, corr:3, manu:2, recy:2} }),

perovskite: M({ id:'perovskite', code:'MAT-088', name:'Halide Perovskite', formula:'e.g. CH₃NH₃PbI₃', family:'energy', cls:'Hybrid photovoltaic crystal',
  rarity:'epic', region:'nexus', color:'#e8b8f8', specimen:'gem',
  summary:'The fastest-improving solar material in history — solution-printed crystals with a tunable bandgap.',
  desc:'ABX₃ crystals whose bandgap tunes with halide mix. Lab cells leapt from 3.8% (2009) past 26% efficiency in a decade — printable from solution at low temperature. Moisture, heat and lead content stand between them and ubiquity.',
  bonding:{hybrid:'Ionic framework + organic cation', structure:'ABX₃ perovskite lattice', note:'Corner-sharing PbI₆ octahedra; soft, defect-tolerant lattice.'},
  props:[
    {k:'Bandgap', v:'1.5–2.3', u:'eV (composition-tuned)', kind:'lit', icon:'ele'},
    {k:'Cell efficiency (lab)', v:'>26', u:'% (single junction record)', kind:'lit', icon:'opt'},
    {k:'Carrier diffusion length', v:'>1', u:'µm', kind:'lit', icon:'ele'},
  ],
  radar:{strength:2, conductivity:6, flexibility:4, stability:2.5, sustainability:4, affordability:8},
  apps:['Solar Cells','LEDs','Photodetectors','X-ray Imaging'],
  synth:[{n:'Solution spin-coating', d:'Room-temperature crystallisation from precursor inks.'},{n:'Vapour deposition', d:'Conformal films for tandems.'}],
  limitations:['Degrades with moisture, oxygen, UV and heat','Most efficient versions contain lead','Ion migration causes hysteresis'],
  lore:'A shifting optical crystal that drinks light greedily and gives most of it back as electricity — while it lasts.',
  related:['silicon','gaas'], tags:['solar','optical','printable','energy','tunable'],
  refs:['Kojima et al., J. Am. Chem. Soc. 131, 6050 (2009)','NREL Best Research-Cell Efficiency Chart'],
  sim:{E:15, uts:0.5, failStrain:0.01, ductile:false, conduct:false},
  load:{rho:4100, sigma:10, E:15, tmin:-40, tmax:85, costkg:150, co2:15, fatigue:1, repair:1, corr:1, manu:4, recy:1} }),

sic: M({ id:'sic', code:'MAT-049', name:'Silicon Carbide', formula:'SiC', family:'ceramic', cls:'Wide-bandgap ceramic semiconductor',
  rarity:'rare', region:'ceramic', color:'#6a7080', specimen:'shard',
  summary:'A black crystalline shard that shrugs at heat, voltage and abrasion alike.',
  desc:'Nearly diamond-hard, stable past 1600 °C, and a wide-bandgap semiconductor now displacing silicon in electric-vehicle inverters. Exists in hundreds of polytypes; 4H-SiC rules power electronics.',
  bonding:{hybrid:'sp³ covalent (Si–C)', structure:'Polytypic tetrahedral lattice', note:'~250 known stacking polytypes.'},
  props:[
    {k:'Bandgap', v:'3.26', u:'eV (4H)', kind:'lit', icon:'ele'},
    {k:'Hardness', v:'~9.5', u:'Mohs', kind:'lit', icon:'str'},
    {k:'Max service temp', v:'~1600', u:'°C', kind:'lit', icon:'thm'},
    {k:'Density', v:'3.21', u:'g/cm³', kind:'lit', icon:'den'},
  ],
  radar:{strength:8.5, conductivity:4.5, flexibility:.5, stability:9.5, sustainability:5, affordability:4},
  apps:['EV Power Electronics','Abrasives','Brake Discs','Armour','Mirrors'],
  synth:[{n:'Acheson process', d:'Sand + coke at 2500 °C since 1893.'},{n:'PVT growth', d:'Semiconductor boules by sublimation.'}],
  limitations:['Brittle','Hard to machine','Wafer cost above silicon'],
  lore:'First found in a meteor crater. The Wilds keep their sharpest edges black.',
  related:['diamond','alumina','silicon'], tags:['hard','thermal','power','semiconductor','armour'],
  refs:['Kimoto & Cooper, Fundamentals of SiC Technology (2014)'],
  sim:{E:450, uts:21, failStrain:0.01, ductile:false, conduct:false},
  load:{rho:3210, sigma:550, E:450, tmin:-150, tmax:1600, costkg:80, co2:25, fatigue:3, repair:0, corr:5, manu:2, recy:2} }),

alumina: M({ id:'alumina', code:'MAT-025', name:'Alumina', formula:'Al₂O₃', family:'ceramic', cls:'Oxide ceramic',
  rarity:'uncommon', region:'ceramic', color:'#e0d8c8', specimen:'shard',
  summary:'The default engineering ceramic — hard, inert, insulating, everywhere from spark plugs to hip joints.',
  desc:'Corundum-structured aluminium oxide. As sapphire it armours watch faces; as sintered ceramic it insulates substrates and resists wear in seals and implants.',
  bonding:{hybrid:'Ionic-covalent', structure:'Corundum (hexagonal)', note:'Same crystal as sapphire and ruby.'},
  props:[
    {k:'Hardness', v:'~9', u:'Mohs', kind:'lit', icon:'str'},
    {k:'Compressive strength', v:'2–4', u:'GPa', kind:'lit', icon:'str'},
    {k:'Max service temp', v:'~1700', u:'°C', kind:'lit', icon:'thm'},
    {k:'Density', v:'3.95', u:'g/cm³', kind:'lit', icon:'den'},
  ],
  radar:{strength:7.5, conductivity:.5, flexibility:.5, stability:9.5, sustainability:6, affordability:8},
  apps:['Substrates','Implants','Seals','Cutting Inserts','Insulators'],
  synth:[{n:'Sintering of calcined powder', d:'Pressed and fired near 1600 °C.'}],
  limitations:['Brittle; poor thermal shock vs some ceramics','Low fracture toughness'],
  lore:'Rubies are just alumina that met chromium.',
  related:['zirconia','sic','glass'], tags:['hard','insulator','biocompatible','wear','ceramic'],
  refs:['Auerkari, Mechanical & physical properties of engineering alumina ceramics (1996)'],
  sim:{E:380, uts:0.3, failStrain:0.002, ductile:false, conduct:false},
  load:{rho:3950, sigma:350, E:380, tmin:-150, tmax:1700, costkg:20, co2:12, fatigue:3, repair:0, corr:5, manu:3, recy:2} }),

zirconia: M({ id:'zirconia', code:'MAT-027', name:'Zirconia (YSZ)', formula:'ZrO₂ (Y-stabilised)', family:'ceramic', cls:'Toughened oxide ceramic',
  rarity:'rare', region:'ceramic', color:'#f0ece0', specimen:'shard',
  summary:'The ceramic that fights back — transformation toughening blunts cracks as they run.',
  desc:'Yttria-stabilised zirconia meets an advancing crack tip with a tetragonal→monoclinic phase change that expands and squeezes the crack shut — “ceramic steel”. Also an oxygen-ion conductor at heat, running sensors and fuel cells.',
  bonding:{hybrid:'Ionic', structure:'Stabilised tetragonal/cubic fluorite', note:'Stress-induced phase change toughens.'},
  props:[
    {k:'Fracture toughness', v:'5–10', u:'MPa·m¹ᐟ²', kind:'lit', note:'exceptional for a ceramic', icon:'str'},
    {k:'Flexural strength', v:'0.9–1.2', u:'GPa', kind:'lit', icon:'str'},
    {k:'Density', v:'6.05', u:'g/cm³', kind:'lit', icon:'den'},
  ],
  radar:{strength:8, conductivity:1, flexibility:1, stability:8.5, sustainability:5, affordability:5},
  apps:['Dental Crowns','Thermal Barrier Coatings','Oxygen Sensors','Fuel Cells','Knives'],
  synth:[{n:'Co-precipitation + sintering', d:'3 mol% yttria for 3Y-TZP grades.'}],
  limitations:['Low-temperature hydrothermal ageing','Heavy for a ceramic','Insulating until very hot'],
  lore:'A stone that heals its own wounds — once.',
  related:['alumina','sic'], tags:['tough','biocompatible','thermal','dental','ceramic'],
  refs:['Garvie, Hannink & Pascoe, Nature 258, 703 (1975)'],
  sim:{E:210, uts:1, failStrain:0.005, ductile:false, conduct:false},
  load:{rho:6050, sigma:1000, E:210, tmin:-100, tmax:1200, costkg:60, co2:18, fatigue:4, repair:0, corr:5, manu:3, recy:2} }),

glass: M({ id:'glass', code:'MAT-011', name:'Soda-Lime Glass', formula:'SiO₂·Na₂O·CaO', family:'ceramic', cls:'Amorphous silicate',
  rarity:'common', region:'ceramic', color:'#c8e0e8', specimen:'pane',
  summary:'Humanity’s oldest engineered transparency — a frozen liquid with no crystal lattice at all.',
  desc:'Ninety per cent of manufactured glass: windows, bottles, screens. An amorphous silica network, fluxed by soda, stabilised by lime, floated flat on molten tin. Strong in theory, weak in practice — every scratch is a stress concentrator.',
  bonding:{hybrid:'Covalent network + ionic modifiers', structure:'Amorphous (no long-range order)', note:'Na⁺ breaks the network → lower melting.'},
  props:[
    {k:'Density', v:'2.5', u:'g/cm³', kind:'lit', icon:'den'},
    {k:'Practical tensile strength', v:'30–90', u:'MPa', kind:'lit', note:'pristine fibres reach GPa — flaws decide', icon:'str'},
    {k:'Transparency', v:'~90', u:'% (visible)', kind:'lit', icon:'opt'},
    {k:'Softening point', v:'~700', u:'°C', kind:'lit', icon:'thm'},
  ],
  radar:{strength:3, conductivity:.5, flexibility:1, stability:7, sustainability:7.5, affordability:10},
  apps:['Glazing','Containers','Displays','Optics'],
  synth:[{n:'Float process', d:'Ribbon of melt floated on molten tin (Pilkington, 1959).'}],
  limitations:['Brittle; flaw-controlled strength','Heavy per stiffness','Thermal shock cracks it'],
  lore:'The Wilds grew forests of it where lightning struck the dunes.',
  related:['alumina','aerogel'], tags:['transparent','optical','cheap','recyclable'],
  refs:['Varshneya, Fundamentals of Inorganic Glasses (2006)'],
  sim:{E:70, uts:0.07, failStrain:0.001, ductile:false, conduct:false},
  load:{rho:2500, sigma:50, E:70, tmin:-100, tmax:500, costkg:1, co2:1.4, fatigue:1, repair:0, corr:4, manu:5, recy:5} }),

ti64: M({ id:'ti64', code:'MAT-060', name:'Ti-6Al-4V', formula:'Ti-6Al-4V', family:'metal', cls:'α+β titanium alloy',
  rarity:'rare', region:'foundry', color:'#b8c0cc', specimen:'lattice3d',
  summary:'The aerospace workhorse titanium alloy — half the weight of steel, immune to seawater, friendly to bone.',
  desc:'Six per cent aluminium stabilises the α phase, four per cent vanadium the β; heat treatment tunes the balance. It flies in airframes and jet fans, sails in submarines, and lives inside people as hips and dental roots.',
  bonding:{hybrid:'Metallic', structure:'α (hcp) + β (bcc) two-phase', note:'Microstructure set by thermomechanical processing.'},
  props:[
    {k:'Tensile strength', v:'0.9–1.17', u:'GPa', kind:'lit', icon:'str'},
    {k:'Density', v:'4.43', u:'g/cm³', kind:'lit', icon:'den'},
    {k:'Young’s modulus', v:'~114', u:'GPa', kind:'lit', icon:'str'},
    {k:'Service temp', v:'up to ~400', u:'°C', kind:'lit', icon:'thm'},
  ],
  radar:{strength:8.5, conductivity:2, flexibility:4, stability:9, sustainability:5, affordability:3.5},
  apps:['Airframes','Jet Engines','Implants','Marine','Additive Manufacturing'],
  synth:[{n:'Kroll process + VAR melting', d:'TiCl₄ reduced by Mg; vacuum arc remelted.'},{n:'Powder-bed AM', d:'Now the most 3D-printed structural metal.'}],
  limitations:['Expensive extraction (Kroll bottleneck)','Poor machinability','Galvanic trouble against carbon fibre'],
  lore:'The Foundry’s favourite child — light enough to fly, noble enough to live in the sea.',
  related:['alli','steel','cfrp','nitinol'], tags:['strong','light','aerospace','biocompatible','corrosion','implant'],
  refs:['Boyer, Welsch & Collings, Materials Properties Handbook: Titanium Alloys (1994)'],
  sim:{E:114, uts:0.95, failStrain:0.14, ductile:true, conduct:false},
  load:{rho:4430, sigma:950, E:114, tmin:-250, tmax:400, costkg:18.7, co2:33.8, fatigue:4, repair:2, corr:5, manu:2.5, recy:4} }),

nitinol: M({ id:'nitinol', code:'MAT-031', name:'Nitinol', formula:'NiTi (~50:50 at%)', family:'smart', cls:'Shape-memory alloy',
  rarity:'epic', region:'foundry', color:'#c8d0d8', specimen:'ribbon',
  summary:'A self-folding chrome ribbon — metal with a memory and rubber-like elasticity.',
  desc:'Near-equiatomic nickel-titanium switches between martensite and austenite. Bend it cold, warm it, and it snaps back to its trained shape; above transition it stretches 8% and recovers — superelasticity that makes unbreakable stents and eyeglass frames.',
  bonding:{hybrid:'Metallic (ordered B2)', structure:'Austenite (B2) ⇄ Martensite (B19′)', note:'Diffusionless transformation near body temperature.'},
  props:[
    {k:'Recoverable strain', v:'up to ~8', u:'%', kind:'lit', icon:'str'},
    {k:'Transformation temp', v:'−100 to +100', u:'°C (composition-tuned)', kind:'lit', icon:'thm'},
    {k:'Density', v:'6.45', u:'g/cm³', kind:'lit', icon:'den'},
    {k:'Tensile strength', v:'0.8–1.5', u:'GPa', kind:'lit', icon:'str'},
  ],
  radar:{strength:7, conductivity:3, flexibility:9, stability:7, sustainability:4, affordability:3},
  apps:['Stents','Actuators','Orthodontics','Deployable Space Structures','Eyewear'],
  synth:[{n:'Vacuum induction melting', d:'Composition control to ±0.1 at% — transformation temp shifts ~10 K per 0.1%.'},{n:'Shape training', d:'Constrain + anneal ~500 °C to teach the parent shape.'}],
  limitations:['Nickel sensitivity concerns','Fatigues under large cycling strains','Hysteresis wastes actuation energy'],
  lore:'Discovered by accident at a Navy lab meeting when someone held a lighter under a bent strip. The metal remembered.',
  related:['ti64','steel','liquidmetal'], tags:['smart','actuator','memory','superelastic','implant','biocompatible'],
  refs:['Buehler & Wiley, US Naval Ordnance Lab reports (1961–65)','Otsuka & Wayman, Shape Memory Materials (1998)'],
  sim:{E:75, uts:1.1, failStrain:0.35, ductile:true, conduct:false},
  load:{rho:6450, sigma:900, E:75, tmin:-100, tmax:300, costkg:120, co2:40, fatigue:3, repair:2, corr:4, manu:2, recy:3} }),

steel: M({ id:'steel', code:'MAT-003', name:'Stainless Steel 316L', formula:'Fe-Cr-Ni-Mo', family:'metal', cls:'Austenitic stainless steel',
  rarity:'common', region:'foundry', color:'#aab2bc', specimen:'lattice3d',
  summary:'The dependable austenitic — chromium’s invisible oxide skin heals itself in seconds.',
  desc:'16–18% chromium builds a self-repairing passive film; molybdenum resists chloride pitting; low carbon (“L”) protects welds. Marine hardware, surgical tools, reactors — the default answer when the question is “what won’t rust?”.',
  bonding:{hybrid:'Metallic', structure:'Austenite (fcc)', note:'Cr₂O₃ passive layer ~2 nm, self-healing.'},
  props:[
    {k:'Tensile strength', v:'485–620', u:'MPa (annealed)', kind:'lit', icon:'str'},
    {k:'Density', v:'8.0', u:'g/cm³', kind:'lit', icon:'den'},
    {k:'Elongation', v:'~40', u:'%', kind:'lit', icon:'str'},
  ],
  radar:{strength:6.5, conductivity:2.5, flexibility:6, stability:8.5, sustainability:6.5, affordability:8.5},
  apps:['Marine','Medical Instruments','Food Processing','Architecture','Chemical Plant'],
  synth:[{n:'Electric arc + AOD refining', d:'Largely from recycled scrap.'}],
  limitations:['Heavy','Chloride stress-corrosion cracking above ~60 °C','Work-hardens while machining'],
  lore:'The Foundry’s honest servant. Not brilliant at anything; unwilling to fail at most things.',
  related:['ti64','alli','nitinol'], tags:['corrosion','marine','cheap','tough','recyclable','implant'],
  refs:['ASM Handbook Vol. 1, Properties and Selection: Irons, Steels'],
  sim:{E:193, uts:0.55, failStrain:0.4, ductile:true, conduct:false},
  load:{rho:8000, sigma:550, E:193, tmin:-200, tmax:800, costkg:4.5, co2:6.2, fatigue:4, repair:5, corr:5, manu:5, recy:5} }),

alli: M({ id:'alli', code:'MAT-064', name:'Al-Li Alloy 2195', formula:'Al-Cu-Li', family:'metal', cls:'Aluminium-lithium alloy',
  rarity:'rare', region:'foundry', color:'#ccd4dc', specimen:'lattice3d',
  summary:'Every 1% lithium buys 3% less weight and 6% more stiffness — rocket-tank aluminium.',
  desc:'Lithium is the lightest metallic element; alloyed into aluminium it cuts density and raises modulus simultaneously. 2195 built the Space Shuttle’s super-lightweight tank, saving 3,400 kg, and now flies in Falcon 9 and Orion.',
  bonding:{hybrid:'Metallic + T₁ precipitates', structure:'fcc matrix, Al₂CuLi platelets', note:'T₁ precipitates give the strength.'},
  props:[
    {k:'Density', v:'2.7', u:'g/cm³', kind:'lit', icon:'den'},
    {k:'Tensile strength', v:'~590', u:'MPa (T8)', kind:'lit', icon:'str'},
    {k:'Young’s modulus', v:'~78', u:'GPa', kind:'lit', icon:'str'},
  ],
  radar:{strength:7, conductivity:4, flexibility:5, stability:7.5, sustainability:5.5, affordability:5},
  apps:['Rocket Tanks','Fuselage Panels','Wing Structures'],
  synth:[{n:'DC casting under inert gas', d:'Lithium burns — the melt shop works blanketed in argon.'}],
  limitations:['Anisotropic properties','Costly lithium handling','Lower damage tolerance in old generations'],
  lore:'The alloy that lightened a Shuttle by three and a half tonnes without changing its shape.',
  related:['ti64','steel','cfrp'], tags:['light','aerospace','strong','cryogenic'],
  refs:['Rioja & Liu, Metall. Mater. Trans. A 43, 3325 (2012)'],
  sim:{E:78, uts:0.59, failStrain:0.1, ductile:true, conduct:false},
  load:{rho:2700, sigma:590, E:78, tmin:-196, tmax:150, costkg:9.6, co2:19.6, fatigue:3, repair:4, corr:3.5, manu:4, recy:4.5} }),

cfrp: M({ id:'cfrp', code:'MAT-070', name:'Carbon Fibre Composite', formula:'C fibre / epoxy', family:'composite', cls:'Fibre-reinforced polymer',
  rarity:'rare', region:'composite', color:'#3a3f4a', specimen:'weave',
  summary:'A dark woven monolith — stiffness where you point it, lightness everywhere else.',
  desc:'Thousands of 5–7 µm carbon filaments locked in epoxy. Strength follows the fibres: laminates are engineered ply by ply, orientation by orientation. Half the Boeing 787 by weight; every Formula 1 tub.',
  bonding:{hybrid:'Covalent fibre + crosslinked matrix', structure:'Laminated unidirectional/woven plies', note:'Anisotropy is a design variable, not a flaw.'},
  props:[
    {k:'Tensile strength', v:'0.6–3.5', u:'GPa (layup dep.)', kind:'lit', icon:'str'},
    {k:'Density', v:'1.55–1.6', u:'g/cm³', kind:'lit', icon:'den'},
    {k:'Specific stiffness', v:'~113', u:'GPa/(g/cm³) quasi-iso ~45', kind:'calc', icon:'str'},
    {k:'Service temp', v:'−50 to 150 (epoxy)', u:'°C', kind:'lit', icon:'thm'},
  ],
  radar:{strength:9, conductivity:3, flexibility:3.5, stability:6.5, sustainability:3, affordability:4},
  apps:['Aerospace','Motorsport','Wind Blades','Bicycles','Pressure Vessels'],
  synth:[{n:'PAN pyrolysis → prepreg → autoclave', d:'Fibre carbonised at up to 3000 °C, laid up, cured under pressure.'},{n:'Resin transfer moulding', d:'Faster, cheaper, automotive-scale.'}],
  limitations:['Delamination hides beneath the surface','Recycling remains poor','Galvanic attack on aluminium/steel fasteners','Costly energy-intense fibre'],
  lore:'The Frontier folds its terrain from this — strong along the weave, secretive across it.',
  related:['cnt','ti64','kevlar','alli'], tags:['strong','light','aerospace','stiff','anisotropic'],
  refs:['Gay, Composite Materials: Design and Applications (2014)'],
  sim:{E:135, uts:2.2, failStrain:0.016, ductile:false, conduct:false},
  load:{rho:1580, sigma:2450, E:135, tmin:-50, tmax:150, costkg:28.4, co2:14.2, fatigue:5, repair:2, corr:5, manu:2, recy:1} }),

kevlar: M({ id:'kevlar', code:'MAT-072', name:'Kevlar 49', formula:'Aramid (PPTA)', family:'polymer', cls:'Aromatic polyamide fibre',
  rarity:'rare', region:'polymer', color:'#d8c060', specimen:'weave',
  summary:'The fibre that stops bullets by refusing to let its hydrogen bonds go quietly.',
  desc:'Rigid aromatic chains, spun from sulfuric acid solution, align almost perfectly along the fibre. Sheets of hydrogen bonds spread impact energy sideways through the weave — body armour, cables, and the rip-stop skin of Mars landers.',
  bonding:{hybrid:'Covalent chains + H-bond sheets', structure:'Liquid-crystalline aligned fibrils', note:'Radial pleated sheet structure.'},
  props:[
    {k:'Tensile strength', v:'~3.6', u:'GPa (fibre)', kind:'lit', icon:'str'},
    {k:'Density', v:'1.44', u:'g/cm³', kind:'lit', icon:'den'},
    {k:'Modulus', v:'~112', u:'GPa (Kevlar 49)', kind:'lit', icon:'str'},
  ],
  radar:{strength:8.5, conductivity:.5, flexibility:7, stability:6, sustainability:3.5, affordability:5},
  apps:['Ballistic Armour','Ropes & Cables','Tyres','Spacecraft Shielding'],
  synth:[{n:'Dry-jet wet spinning', d:'From concentrated H₂SO₄ lyotropic solution (Kwolek, 1965).'}],
  limitations:['UV degrades it','Absorbs moisture','Weak in compression','Hard to cut cleanly'],
  lore:'Stephanie Kwolek’s cloudy solution that everyone else would have thrown away.',
  related:['cfrp','pla','peek'], tags:['strong','impact','fibre','armour','light'],
  refs:['Kwolek patents (DuPont, 1971)','Yang, Kevlar Aramid Fiber (1993)'],
  sim:{E:112, uts:3.6, failStrain:0.024, ductile:false, conduct:false},
  load:{rho:1440, sigma:3000, E:112, tmin:-70, tmax:180, costkg:35, co2:20, fatigue:4, repair:2, corr:4, manu:3, recy:1.5} }),

pla: M({ id:'pla', code:'MAT-078', name:'PLA', formula:'(C₃H₄O₂)ₙ', family:'polymer', cls:'Biodegradable polyester',
  rarity:'common', region:'polymer', color:'#a8d8a0', specimen:'coil',
  summary:'Corn-starch plastic — the desktop 3D-printing default that composts back to CO₂ and water.',
  desc:'Polylactic acid ferments from plant sugars and prints at a friendly 200 °C. Industrially compostable (not backyard-compostable), stiff but brittle, softening near 60 °C — the gateway polymer of distributed manufacturing.',
  bonding:{hybrid:'Covalent ester backbone', structure:'Semi-crystalline polyester', note:'L/D isomer ratio controls crystallinity.'},
  props:[
    {k:'Tensile strength', v:'50–70', u:'MPa', kind:'lit', icon:'str'},
    {k:'Density', v:'1.24', u:'g/cm³', kind:'lit', icon:'den'},
    {k:'Glass transition', v:'~60', u:'°C', kind:'lit', icon:'thm'},
  ],
  radar:{strength:3, conductivity:.5, flexibility:3, stability:3, sustainability:8.5, affordability:9},
  apps:['3D Printing','Food Packaging','Medical Sutures','Drug Delivery'],
  synth:[{n:'Fermentation → lactide → ROP', d:'Sugar to lactic acid to ring-opened polymer.'}],
  limitations:['Softens at ~60 °C','Brittle without plasticisers','Composts only industrially (~58 °C facilities)'],
  lore:'The Canopy grows spools of it for travellers who promise to bring the carbon back.',
  related:['peek','cellulose','mycelium'], tags:['biodegradable','printable','cheap','sustainable','packaging','biocompatible'],
  refs:['Garlotta, J. Polym. Environ. 9, 63 (2001)'],
  sim:{E:3.5, uts:0.06, failStrain:0.04, ductile:true, conduct:false},
  load:{rho:1240, sigma:60, E:3.5, tmin:-20, tmax:55, costkg:2.5, co2:0.6, fatigue:2, repair:3, corr:3, manu:5, recy:4} }),

peek: M({ id:'peek', code:'MAT-079', name:'PEEK', formula:'(C₁₉H₁₂O₃)ₙ', family:'polymer', cls:'High-performance thermoplastic',
  rarity:'rare', region:'polymer', color:'#c8b890', specimen:'coil',
  summary:'The aristocrat of thermoplastics — flies in engines, survives autoclaves, replaces bone.',
  desc:'An aromatic backbone gives PEEK a 143 °C glass transition and continuous service at 250 °C, chemical near-immunity, and a stiffness close enough to bone that spine surgeons prefer it to titanium.',
  bonding:{hybrid:'Covalent aromatic ketone-ether', structure:'Semi-crystalline (~35%)', note:'Aromatic rings give thermal backbone.'},
  props:[
    {k:'Tensile strength', v:'~100', u:'MPa', kind:'lit', icon:'str'},
    {k:'Continuous service', v:'~250', u:'°C', kind:'lit', icon:'thm'},
    {k:'Density', v:'1.32', u:'g/cm³', kind:'lit', icon:'den'},
  ],
  radar:{strength:5, conductivity:.5, flexibility:5, stability:8.5, sustainability:4, affordability:2.5},
  apps:['Aerospace Brackets','Spinal Implants','Seals','Downhole Tools'],
  synth:[{n:'Nucleophilic polycondensation', d:'~300 °C in diphenyl sulfone.'}],
  limitations:['~100× the price of commodity plastics','Needs 400 °C processing','UV sensitive outdoors'],
  lore:'Plastic that forgot it was supposed to be the cheap option.',
  related:['pla','kevlar','ti64'], tags:['thermal','implant','biocompatible','chemical','aerospace'],
  refs:['Kurtz, PEEK Biomaterials Handbook (2012)'],
  sim:{E:3.9, uts:0.1, failStrain:0.45, ductile:true, conduct:false},
  load:{rho:1320, sigma:100, E:3.9, tmin:-60, tmax:250, costkg:90, co2:25, fatigue:4, repair:3, corr:5, manu:3.5, recy:3} }),

silicone: M({ id:'silicone', code:'MAT-080', name:'Silicone (PDMS)', formula:'(C₂H₆OSi)ₙ', family:'polymer', cls:'Inorganic-backbone elastomer',
  rarity:'common', region:'polymer', color:'#e8d8e0', specimen:'membrane',
  summary:'The rubber with a stone spine — flexible at −60 °C, calm at 230 °C, at home inside the body.',
  desc:'A silicon-oxygen backbone (not carbon) gives silicone its huge temperature span, UV indifference and biocompatibility. Soft lithography built microfluidics from it; medicine builds implants; kitchens build spatulas.',
  bonding:{hybrid:'Si–O backbone, organic side groups', structure:'Crosslinked amorphous network', note:'Backbone bond energy > C–C → stability.'},
  props:[
    {k:'Elongation', v:'100–800', u:'%', kind:'lit', icon:'str'},
    {k:'Service range', v:'−60 to 230', u:'°C', kind:'lit', icon:'thm'},
    {k:'Density', v:'~1.03', u:'g/cm³', kind:'lit', icon:'den'},
  ],
  radar:{strength:1.5, conductivity:.5, flexibility:10, stability:7.5, sustainability:5, affordability:7},
  apps:['Medical Implants','Microfluidics','Seals','Soft Robotics','Cookware'],
  synth:[{n:'Hydrosilylation cure', d:'Pt-catalysed crosslinking; castable at room temp.'}],
  limitations:['Low tear strength','Swells in solvents','Hard to bond without plasma'],
  lore:'The Canopy’s membranes breathe through it.',
  related:['hydrogel','pedot','liquidmetal'], tags:['flexible','biocompatible','soft','seal','stretchable','wearable'],
  refs:['Xia & Whitesides, Angew. Chem. 37, 550 (1998)'],
  sim:{E:0.002, uts:0.007, failStrain:4, ductile:true, conduct:false},
  load:{rho:1030, sigma:7, E:0.002, tmin:-60, tmax:230, costkg:8, co2:3.5, fatigue:4, repair:3, corr:4, manu:5, recy:2} }),

hydrogel: M({ id:'hydrogel', code:'MAT-090', name:'Hydrogel (PVA/alginate)', formula:'Polymer + H₂O', family:'bio', cls:'Water-swollen network',
  rarity:'rare', region:'bio', color:'#a0e0e8', specimen:'membrane',
  summary:'A translucent breathing membrane — up to 90% water held in a molecular net, soft as living tissue.',
  desc:'Crosslinked hydrophilic chains that drink water without dissolving. Tissue-like moduli make hydrogels the bridge between machines and biology: contact lenses, wound dressings, drug depots, and the scaffolds where new organs are grown.',
  bonding:{hybrid:'Covalent/ionic crosslinks + H-bonded water', structure:'Swollen 3D network', note:'Double-network gels reach cartilage toughness.'},
  props:[
    {k:'Water content', v:'70–99', u:'%', kind:'lit', icon:'den'},
    {k:'Elastic modulus', v:'1–1000', u:'kPa (tissue-like)', kind:'lit', icon:'str'},
    {k:'Fracture energy (DN gels)', v:'~1000', u:'J/m²', kind:'lit', icon:'str'},
  ],
  radar:{strength:1, conductivity:2, flexibility:9.5, stability:2.5, sustainability:8, affordability:8},
  apps:['Wound Care','Contact Lenses','Tissue Scaffolds','Soft Actuators','Agriculture'],
  synth:[{n:'Ionic gelation', d:'Alginate + Ca²⁺ — instant gel, no heat.'},{n:'Freeze-thaw PVA', d:'Physical crystallite crosslinks.'}],
  limitations:['Dries out unsealed','Weak unless double-networked','Sterilisation can alter structure'],
  lore:'The Depths breathe through membranes like this. Squeeze one and it exhales.',
  related:['cellulose','silicone','mycelium'], tags:['soft','biocompatible','wet','medical','tissue'],
  refs:['Wichterle & Lím, Nature 185, 117 (1960)','Gong et al., Adv. Mater. 15, 1155 (2003)'],
  sim:{E:0.0001, uts:0.0002, failStrain:2, ductile:true, conduct:false},
  load:{rho:1050, sigma:0.2, E:0.0001, tmin:0, tmax:60, costkg:5, co2:1, fatigue:2, repair:4, corr:3, manu:5, recy:4} }),

cellulose: M({ id:'cellulose', code:'MAT-092', name:'Cellulose Nanofibre', formula:'(C₆H₁₀O₅)ₙ', family:'bio', cls:'Nanoscale biopolymer',
  rarity:'rare', region:'bio', color:'#d8f0c8', specimen:'bloom',
  summary:'A luminous woven bloom — wood, deconstructed to nanofibrils stronger than steel by weight.',
  desc:'Plants wind glucose chains into 3–20 nm crystalline fibrils; a tree is a hierarchical composite of them. Liberated by fibrillation, CNF forms transparent films and aerogels — renewable nanotechnology grown by photosynthesis.',
  bonding:{hybrid:'Covalent chains + dense H-bonding', structure:'Crystalline nanofibrils', note:'Hierarchy: chain → fibril → fibre → wood.'},
  props:[
    {k:'Tensile strength (fibril)', v:'1–3', u:'GPa', kind:'lit', icon:'str'},
    {k:'Modulus (crystal)', v:'~140', u:'GPa', kind:'lit', icon:'str'},
    {k:'Density', v:'1.5', u:'g/cm³', kind:'lit', icon:'den'},
  ],
  radar:{strength:6.5, conductivity:.5, flexibility:6.5, stability:4, sustainability:10, affordability:6},
  apps:['Barrier Packaging','Transparent Films','Composites','Rheology Modifiers','Scaffolds'],
  synth:[{n:'TEMPO oxidation + fibrillation', d:'Chemistry loosens, shear liberates.'}],
  limitations:['Loves water too much','Energy-hungry fibrillation','Thermal limit ~200 °C'],
  lore:'Every tree was already a nanomaterial factory; we only just learned to ask.',
  related:['mycelium','pla','hydrogel','aerogel'], tags:['sustainable','renewable','strong','transparent','packaging','bio'],
  refs:['Saito et al., Biomacromolecules 8, 2485 (2007)','Moon et al., Chem. Soc. Rev. 40, 3941 (2011)'],
  sim:{E:140, uts:2, failStrain:0.05, ductile:false, conduct:false},
  load:{rho:1500, sigma:1500, E:140, tmin:-40, tmax:200, costkg:15, co2:0.9, fatigue:3, repair:2, corr:2, manu:3, recy:5} }),

mycelium: M({ id:'mycelium', code:'MAT-095', name:'Mycelium Composite', formula:'Fungal hyphae + substrate', family:'bio', cls:'Grown biocomposite',
  rarity:'rare', region:'bio', color:'#e0d0b8', specimen:'reef',
  summary:'A material you don’t manufacture — you feed it, and it grows into the mould.',
  desc:'Fungal root networks digest agricultural waste and bind it into foam-like solids. Grown in days, heat-killed, compostable in weeks — already shipping as packaging (Ecovative/IKEA) and prototyped as leather, insulation and acoustic panels.',
  bonding:{hybrid:'Chitin-wall hyphal network', structure:'Random fibrous foam', note:'Density set by substrate and growth time.'},
  props:[
    {k:'Density', v:'0.06–0.3', u:'g/cm³', kind:'lit', icon:'den'},
    {k:'Compressive strength', v:'0.1–1', u:'MPa', kind:'lit', icon:'str'},
    {k:'Thermal conductivity', v:'~0.04', u:'W/m·K', kind:'lit', icon:'thm'},
  ],
  radar:{strength:1, conductivity:.5, flexibility:3, stability:2, sustainability:10, affordability:9},
  apps:['Protective Packaging','Insulation','Acoustic Panels','Vegan Leather'],
  synth:[{n:'Inoculate + grow + heat-kill', d:'5–10 days in a mould, then dried.'}],
  limitations:['Weak and water-sensitive','Batch variability — it is alive','Slow vs injection moulding'],
  lore:'The Depths’ oldest architect. It was recycling forests before vertebrates existed.',
  related:['cellulose','pla','aerogel'], tags:['sustainable','grown','compostable','packaging','insulation','bio'],
  refs:['Jones et al., Materials & Design 187, 108397 (2020)'],
  sim:{E:0.01, uts:0.0005, failStrain:0.1, ductile:true, conduct:false},
  load:{rho:150, sigma:0.5, E:0.01, tmin:-20, tmax:80, costkg:3, co2:0.1, fatigue:1, repair:1, corr:1, manu:4, recy:5} }),
};

const MAT_LIST = Object.keys(MATERIALS);

/* achievements */
const ACHIEVEMENTS = [
  {id:'first_scan',  n:'First Structure Scanned', d:'Resolve your first lattice.', sig:'hex'},
  {id:'carbon_cart', n:'Carbon Cartographer', d:'Collect every Carbon Form and Graphene.', sig:'tri'},
  {id:'defect_det',  n:'Defect Detective', d:'Inspect a crack tip during a critical event.', sig:'eye'},
  {id:'iface_arch',  n:'Interface Architect', d:'Resolve a loadout compatibility risk.', sig:'link'},
  {id:'ten_sims',    n:'Ten Simulations Completed', d:'Run the lab protocol ten times.', sig:'wave'},
  {id:'zero_fail',   n:'Zero-Failure Loadout', d:'Submit the aerospace quest with no unresolved risks.', sig:'shield'},
  {id:'sustain',     n:'Sustainable Systems Designer', d:'Submit a loadout with sustainability above 60.', sig:'leaf'},
  {id:'prop_explorer',n:'Property Space Explorer', d:'Chart materials across three different axis pairs.', sig:'axes'},
  {id:'bandgap',     n:'The Violet Bandgap', d:'Recover the anomalous crystal from the Nexus.', sig:'crystal'},
  {id:'matter_weaver',n:'Matter Weaver', d:'Reach 12 collected materials.', sig:'weave'},
];

/* ranks */
const RANKS = [
  {n:'Observer', xp:0},{n:'Analyst', xp:600},{n:'Researcher', xp:1600},
  {n:'Materials Cartographer', xp:3200},{n:'Structure Weaver', xp:5600},
  {n:'Systems Architect', xp:9000},{n:'Matter Pioneer', xp:14000},
];

/* collection sets */
const SETS = [
  {id:'carbon',  n:'Carbon Forms',       ids:['graphene','cnt','diamond','cfrp'], bonus:'+10% scan XP on carbon materials'},
  {id:'smart',   n:'Smart Materials',    ids:['nitinol','liquidmetal','hydrogel'], bonus:'Unlocks actuator challenge'},
  {id:'energy',  n:'Energy Crystals',    ids:['perovskite','silicon','gaas'], bonus:'+5% expedition scan confidence'},
  {id:'wilds',   n:'Ceramic Wilds',      ids:['aerogel','sic','alumina','zirconia','glass'], bonus:'+10% thermal resistance across builds'},
  {id:'nanobio', n:'Nano Biostructures', ids:['cellulose','mycelium','hydrogel'], bonus:'+10% sustainability scoring'},
  {id:'aero',    n:'Aerospace Alloys',   ids:['ti64','alli','steel'], bonus:'−5% loadout cost estimates'},
  {id:'electro', n:'Electronic Materials',ids:['silicon','gaas','mxene','pedot'], bonus:'Reveals band structures in Atlas'},
];

/* challenges */
const CHALLENGES = [
  {id:'aeroshell', n:'Lighter Aerospace Shell', brief:'Reduce airframe mass by 25% while maintaining structural integrity.', tags:['Structures','Trade-offs'], rank:0, go:'loadout',
   detail:'The Orion Mk. III shell is over mass budget. Use the Loadout Builder: assign materials to nose, skin, frame, thermal shield and joints. Watch safety margin, temperature windows and interface compatibility. Mass target −25% against the all-titanium baseline.'},
  {id:'wearable', n:'Flexible Wearable Sensor', brief:'Choose a conductor and substrate for a skin-mounted strain sensor.', tags:['Electronics','Flexibility'], rank:1, go:null,
   detail:'Pick one conductive material and one substrate. Scored on flexibility, conductivity, biocompatibility and cost. There is no single right answer — defend a trade-off.',
   pick:{roles:['Conductor','Substrate'], score:(c,s)=>{
     const R=MATERIALS; let sc=0, notes=[];
     sc += (R[c].radar.conductivity*2.2) + (R[c].radar.flexibility*1.8);
     sc += (R[s].radar.flexibility*2.2) + (R[s].radar.sustainability*.6) + (R[s].radar.affordability*.8);
     if(R[c].tags.includes('wearable')) {sc+=8; notes.push(R[c].name+' is proven in wearables.');}
     if(R[s].tags.includes('biocompatible')) {sc+=8; notes.push(R[s].name+' is skin-safe.');}
     if(!R[s].tags.includes('flexible')&&R[s].radar.flexibility<6) notes.push('Substrate stiffness will crack the sensor at joint lines.');
     if(R[c].id==='graphene'&&R[s].id==='silicone') notes.push('A classic lab pairing — graphene on PDMS.');
     return {score:Math.min(100,Math.round(sc)), notes};
   }}},
  {id:'marine', n:'Corrosion-Resistant Marine Structure', brief:'Select a hull bracket material for 25 years in seawater.', tags:['Corrosion','Cost'], rank:1, go:null,
   pick:{roles:['Structure'], score:(a)=>{
     const m=MATERIALS[a]; let sc=m.load.corr*12 + m.radar.strength*3 + m.radar.affordability*2.5; let notes=[];
     if(m.id==='steel') notes.push('316L is the industry default — watch chloride SCC above 60 °C.');
     if(m.id==='ti64') notes.push('Titanium is immune to seawater but triples the budget.');
     if(m.load.corr<3) notes.push('This material will not survive the salt.');
     return {score:Math.min(100,Math.round(sc)), notes};
   }}},
  {id:'electrode', n:'Transparent Conductive Electrode', brief:'Replace indium tin oxide in a foldable display.', tags:['Optics','Electronics'], rank:2, go:null,
   pick:{roles:['Electrode'], score:(a)=>{
     const m=MATERIALS[a]; let sc=m.radar.conductivity*4+m.radar.flexibility*4; let notes=[];
     if(m.tags.includes('transparent')) {sc+=20; notes.push('Optically viable.');} else notes.push('Opaque — fails the primary requirement.');
     return {score:Math.min(100,Math.round(sc)), notes};
   }}},
  {id:'thermal', n:'Spacecraft Thermal Protection', brief:'Insulate a re-entry body without breaking the mass budget.', tags:['Thermal','Aerospace'], rank:2, go:null,
   pick:{roles:['Insulator'], score:(a)=>{
     const m=MATERIALS[a]; let sc=(10-m.radar.conductivity)*3 + (m.load.tmax>1000?30:m.load.tmax/40) + (m.load.rho<500?25:2000/m.load.rho); let notes=[];
     if(m.id==='aerogel') notes.push('The classic answer — fragile, so it needs a facing layer.');
     if(m.load.tmax<600) notes.push('Service ceiling too low for re-entry heating alone; usable only behind an ablator.');
     return {score:Math.min(100,Math.round(sc)), notes};
   }}},
  {id:'package', n:'Biodegradable Food Package', brief:'Ship berries 500 km, then vanish.', tags:['Sustainability'], rank:3, go:null,
   pick:{roles:['Package'], score:(a)=>{
     const m=MATERIALS[a]; let sc=m.radar.sustainability*5+m.radar.affordability*3; let notes=[];
     if(m.tags.includes('compostable')||m.tags.includes('biodegradable')) {sc+=15; notes.push('Genuine end-of-life pathway.');}
     if(m.id==='mycelium') notes.push('Grown to shape, composts in weeks — Ecovative ships exactly this.');
     return {score:Math.min(100,Math.round(sc)), notes};
   }}},
  {id:'implant', n:'Hip Implant Stem', brief:'Choose a femoral stem material a body will tolerate for 20 years.', tags:['Biomaterials'], rank:3, go:null,
   pick:{roles:['Stem'], score:(a)=>{
     const m=MATERIALS[a]; let sc=m.radar.strength*3+m.load.corr*8; let notes=[];
     if(m.tags.includes('biocompatible')||m.tags.includes('implant')) {sc+=25; notes.push('Clinically proven biocompatibility.');} else notes.push('No biocompatibility record — regulatory dead end.');
     if(m.id==='ti64') notes.push('The clinical standard — though its stiffness still shields bone from load.');
     if(m.id==='peek') notes.push('Modulus closer to bone reduces stress shielding.');
     return {score:Math.min(100,Math.round(sc)), notes};
   }}},
  {id:'battery', n:'Battery Electrode Optimisation', brief:'Balance conductivity, surface area and swelling.', tags:['Energy'], rank:4, go:null, locked:true},
  {id:'solar', n:'Low-Cost Solar Absorber', brief:'Efficiency per dollar, not efficiency at any price.', tags:['Energy','Optics'], rank:4, go:null, locked:true},
  {id:'actuator', n:'Shape-Memory Actuator', brief:'Engineer a valve that opens itself at 70 °C.', tags:['Smart Materials'], rank:5, go:null, locked:true},
];
