'use strict';
/* Scientific structure records. Coordinates are fractional when a lattice is present,
   otherwise Cartesian model coordinates in arbitrary display units. */
const ELEMENTS={
 H:{name:'Hydrogen',color:'#f4f0e8',radius:.25},C:{name:'Carbon',color:'#556170',radius:.70},N:{name:'Nitrogen',color:'#3b70d9',radius:.65},O:{name:'Oxygen',color:'#e84b4b',radius:.60},
 F:{name:'Fluorine',color:'#74d66a',radius:.50},Na:{name:'Sodium',color:'#9b67d5',radius:1.00},Ca:{name:'Calcium',color:'#8acb5a',radius:1.35},Al:{name:'Aluminium',color:'#aeb9c7',radius:1.18},Si:{name:'Silicon',color:'#e1a642',radius:1.11},
 S:{name:'Sulfur',color:'#e7cf3b',radius:1.00},Ti:{name:'Titanium',color:'#4f83cc',radius:1.20},V:{name:'Vanadium',color:'#8a91a8',radius:1.22},Cr:{name:'Chromium',color:'#3aa7a3',radius:1.18},Fe:{name:'Iron',color:'#d57939',radius:1.17},
 Ni:{name:'Nickel',color:'#57a86b',radius:1.15},Cu:{name:'Copper',color:'#c36c3e',radius:1.17},Ga:{name:'Gallium',color:'#c266c9',radius:1.21},As:{name:'Arsenic',color:'#7655ad',radius:1.14},
 Zr:{name:'Zirconium',color:'#35a9ad',radius:1.45},Y:{name:'Yttrium',color:'#7fbe45',radius:1.62},Mo:{name:'Molybdenum',color:'#4cb7c8',radius:1.30},In:{name:'Indium',color:'#5c69bd',radius:1.42},
 I:{name:'Iodine',color:'#8a4bb0',radius:1.40},Pb:{name:'Lead',color:'#697483',radius:1.54},Li:{name:'Lithium',color:'#e78aa7',radius:1.28}
};
const STRUCTURE_TYPES=['crystal lattice','molecular structure','polymer chain','atomic network','layered structure','representative microstructure','representative model','unavailable'];
const src=(citation,url,kind='primary crystallographic record')=>({citation,url,kind});
const atom=(element,position,role,occupancy=1)=>({element,position,role,occupancy});
const frac=(element,fractional,role,occupancy=1)=>({element,fractional,role,occupancy});
const MP='https://optimade.materialsproject.org/v1/structures/';
const crystal=(o)=>Object.assign({exact:true,repeat:[2,2,2],bonds:[],defects:[],limitations:[]},o);
const representative=(o)=>Object.assign({exact:false,lattice:null,bonds:[],defects:[],limitations:[]},o);

const STRUCTURE_DATA={
 graphene:crystal({representation:'layered structure',structureType:'Hexagonal layered',phase:'monolayer graphene',composition:'C',lattice:{vectors:[[2.46,0,0],[1.23,2.1304,0],[0,0,12]],unit:'Å'},repeat:[5,5,1],atoms:[frac('C',[0,0,.5],'sp² carbon'),frac('C',[1/3,1/3,.5],'sp² carbon')],bondRules:[{pair:['C','C'],min:1.39,max:1.45,coordination:3,label:'sp² C–C'}],source:src('Castro Neto et al., Rev. Mod. Phys. 81, 109 (2009), aCC = 1.42 Å','https://doi.org/10.1103/RevModPhys.81.109','peer-reviewed structural reference'),modellingNotes:'Ideal flat primitive cell; thermal ripples are omitted.',limitations:['Ideal defect-free monolayer.']}),
 cnt:representative({representation:'layered structure',structureType:'Hexagonal layered',phase:'single-wall (10,0) zigzag nanotube',composition:'C',model:{kind:'nanotube',n:10,rows:8,bondLength:1.42},elements:['C'],source:src('Saito, Dresselhaus & Dresselhaus, Physical Properties of Carbon Nanotubes (1998)','https://doi.org/10.1142/p080','derived from graphene lattice'),modellingNotes:'Graphene is rolled with declared (10,0) chirality; not a generic cylinder.',limitations:['One representative chirality.']}),
 diamond:crystal({representation:'crystal lattice',structureType:'Diamond cubic',phase:'cubic Fd-3m',composition:'C',lattice:{vectors:[[2.180502,0,1.258913],[.726834,2.055797,1.258913],[0,0,2.517827]],unit:'Å'},atoms:[frac('C',[.875,.875,.875],'tetrahedral carbon'),frac('C',[.125,.125,.125],'tetrahedral carbon')],bondRules:[{pair:['C','C'],min:1.50,max:1.58,coordination:4,label:'sp³ C–C'}],source:src('Materials Project mp-66, diamond C',MP+'mp-66'),modellingNotes:'Primitive cell from Materials Project OPTIMADE.',limitations:[]}),
 aerogel:representative({representation:'atomic network',structureType:'Amorphous network',phase:'amorphous silica aerogel',composition:'SiO₂ skeleton + void',model:{kind:'aerogel'},elements:['Si','O'],source:src('Woignier et al., J. Sol-Gel Sci. Technol. 76, 521–532 (2015)','https://doi.org/10.1007/s10971-015-3799-7','mesoscale morphology reference'),modellingNotes:'Deterministic pearl-necklace network represents mesoscale silica clusters, not atom-exact coordinates.',limitations:['Pore topology depends on synthesis.']}),
 mxene:crystal({representation:'layered structure',structureType:'Hexagonal layered',phase:'Ti₃C₂ backbone; representative O/F terminations',composition:'Ti₃C₂O₀.₅F₀.₅ (display model)',lattice:{vectors:[[1.533303,-2.655757,0],[1.533303,2.655757,0],[0,0,15.11715]],unit:'Å'},repeat:[3,3,1],atoms:[frac('Ti',[2/3,1/3,.343878],'outer Ti'),frac('Ti',[1/3,2/3,.656122],'outer Ti'),frac('Ti',[0,0,.5],'central Ti'),frac('C',[1/3,2/3,.414104],'carbide C'),frac('C',[2/3,1/3,.585896],'carbide C'),frac('O',[0,0,.27],'representative surface termination',.5),frac('F',[0,0,.73],'representative surface termination',.5)],source:src('Materials Project mp-1094034, Ti3C2 backbone',MP+'mp-1094034'),modellingNotes:'Crystalline Ti3C2 backbone is sourced; termination identities/sites are representative and synthesis-dependent.',limitations:['Tx chemistry is not unique.']}),
 pedot:representative({representation:'polymer chain',structureType:'Polymer repeat unit',phase:'PEDOT:PSS blend',composition:'PEDOT repeat unit + PSS domain',model:{kind:'polymer',sequence:['C','C','S','C','C','O'],chains:3,side:['O']},elements:['C','S','O'],source:src('Groenendaal et al., Adv. Mater. 12, 481–494 (2000)','https://doi.org/10.1002/(SICI)1521-4095(200004)12:7%3C481::AID-ADMA481%3E3.0.CO;2-C','polymer chemistry review'),modellingNotes:'Repeat-unit chains and a labelled PSS domain; no periodic blend lattice is claimed.',limitations:['Doping and domain morphology vary.']}),
 liquidmetal:representative({representation:'representative model',structureType:'Representative liquid snapshot',phase:'eutectic Ga–In liquid near 298 K',composition:'Ga 75.5 wt%, In 24.5 wt% (EGaIn)',model:{kind:'liquid',counts:{Ga:38,In:10}},elements:['Ga','In'],source:src('Dickey, Adv. Mater. 29, 1606425 (2017)','https://doi.org/10.1002/adma.201606425','composition and liquid-metal review'),modellingNotes:'Deterministic nonperiodic snapshot communicates composition only; it is not diffraction-refined structure.',limitations:['Liquid coordination is time-dependent.']}),
 silicon:crystal({representation:'crystal lattice',structureType:'Diamond cubic',phase:'cubic Fd-3m',composition:'Si',lattice:{vectors:[[3.333573,0,1.924639],[1.111191,3.142924,1.924639],[0,0,3.849278]],unit:'Å'},atoms:[frac('Si',[.875,.875,.875],'tetrahedral Si'),frac('Si',[.125,.125,.125],'tetrahedral Si')],bondRules:[{pair:['Si','Si'],min:2.30,max:2.40,coordination:4,label:'Si–Si'}],source:src('Materials Project mp-149, silicon',MP+'mp-149'),modellingNotes:'Primitive cell from Materials Project OPTIMADE.',limitations:[]}),
 gaas:crystal({representation:'crystal lattice',structureType:'Zinc blende',phase:'cubic F-43m',composition:'GaAs',lattice:{vectors:[[3.521253,0,2.032997],[1.173751,3.319869,2.032997],[0,0,4.065993]],unit:'Å'},atoms:[frac('Ga',[0,0,0],'Ga sublattice'),frac('As',[.25,.25,.25],'As sublattice')],bondRules:[{pair:['Ga','As'],min:2.40,max:2.50,coordination:4,label:'Ga–As'}],source:src('Materials Project mp-2534, GaAs',MP+'mp-2534'),modellingNotes:'Primitive cell from Materials Project OPTIMADE.',limitations:[]}),
 perovskite:crystal({representation:'crystal lattice',structureType:'Perovskite',phase:'high-temperature alpha MAPbI₃, P4mm, 400 K',composition:'CH₃NH₃PbI₃',lattice:{vectors:[[6.3115,0,0],[0,6.3115,0],[0,0,6.3161]],unit:'Å'},repeat:[2,2,2],atoms:[frac('Pb',[0,0,0],'B-site Pb'),frac('I',[.5,0,0],'equatorial iodide'),frac('I',[0,.5,0],'equatorial iodide'),frac('I',[0,0,.5],'axial iodide'),frac('C',[.5,.5,.5],'methylammonium carbon'),frac('N',[.5,.5,.62],'methylammonium nitrogen')],elements:['Pb','I','C','N','H'],bondRules:[{pair:['Pb','I'],min:2.9,max:3.3,coordination:6,label:'PbI₆ coordination'}],source:src('Stoumpos et al., Inorg. Chem. 52, 9019–9038 (2013), 400 K P4mm','https://doi.org/10.1021/ic401215x'),modellingNotes:'PbI3 framework uses reported cell dimensions; one idealized MA orientation represents orientational disorder.',limitations:['Not the room-temperature tetragonal phase; H atoms omitted.']}),
 sic:crystal({representation:'crystal lattice',structureType:'Zinc blende',phase:'3C-SiC, cubic F-43m',composition:'SiC',lattice:{vectors:[[2.666266,0,1.539368],[.888755,2.513779,1.539368],[0,0,3.078738]],unit:'Å'},atoms:[frac('Si',[.25,.25,.25],'Si sublattice'),frac('C',[0,0,0],'C sublattice')],bondRules:[{pair:['Si','C'],min:1.84,max:1.94,coordination:4,label:'Si–C'}],source:src('Materials Project mp-8062, 3C-SiC',MP+'mp-8062'),modellingNotes:'Primitive cell from Materials Project OPTIMADE.',limitations:['Other SiC polytypes are not shown.']}),
 alumina:crystal({representation:'crystal lattice',structureType:'Corundum',phase:'alpha-Al₂O₃, R-3c',composition:'Al₂O₃',lattice:{vectors:[[4.256773,.000341,2.948067],[1.54451,3.966687,2.948066],[.000497,.000339,5.177956]],unit:'Å'},repeat:[2,2,1],atoms:[frac('Al',[.647904,.647903,.647903],'octahedral Al'),frac('Al',[.852097,.852097,.852097],'octahedral Al'),frac('Al',[.147904,.147903,.147903],'octahedral Al'),frac('Al',[.352097,.352096,.352096],'octahedral Al'),frac('O',[.443855,.056145,.750001],'oxide'),frac('O',[.943855,.250001,.556145],'oxide'),frac('O',[.056144,.75,.443855],'oxide'),frac('O',[.750001,.443856,.056144],'oxide'),frac('O',[.25,.556144,.943855],'oxide'),frac('O',[.556144,.943856,.249999],'oxide')],bondRules:[{pair:['Al','O'],min:1.75,max:2.15,coordination:6,label:'AlO₆ coordination'}],source:src('Materials Project mp-1143, alpha-Al2O3',MP+'mp-1143'),modellingNotes:'Rhombohedral primitive cell from Materials Project OPTIMADE.',limitations:[]}),
 zirconia:crystal({representation:'crystal lattice',structureType:'Fluorite',phase:'cubic yttria-stabilized zirconia',composition:'10.3 mol% Y₂O₃ representative: Zr₂₆Y₆O₆₁',lattice:{vectors:[[5.091,0,0],[0,5.091,0],[0,0,5.091]],unit:'Å'},repeat:[2,2,2],model:{kind:'ysz',base:'fluorite conventional'},atoms:[frac('Zr',[0,0,0],'cation sublattice')],elements:['Zr','Y','O'],defects:[{type:'substitution',count:6,from:'Zr',to:'Y'},{type:'vacancy',element:'O',count:3,role:'charge compensation'}],source:src('Materials Project mp-1565 cubic ZrO2 base; Zhang et al., AIP Advances 6, 095119 (2016), Y substitution and oxygen-vacancy compensation','https://doi.org/10.1063/1.4963202'),modellingNotes:'A deterministic 2×2×2 fluorite conventional supercell substitutes 6 of 32 Zr by Y and removes 3 of 64 O; one representative configuration, not a unique ordering.',limitations:['Defect distribution is one declared configuration.']}),
 glass:representative({representation:'atomic network',structureType:'Amorphous network',phase:'soda-lime silicate glass',composition:'representative Si–O network with Na/Ca modifiers',model:{kind:'glass'},elements:['Si','O','Na','Ca'],source:src('Zachariasen, J. Am. Chem. Soc. 54, 3841–3851 (1932)','https://doi.org/10.1021/ja01349a006','continuous-random-network model'),modellingNotes:'Deterministic continuous-random-network motif; no unit cell or experimentally refined coordinates are claimed.',limitations:['Not a composition-specific molecular-dynamics cell.']}),
 ti64:representative({representation:'representative microstructure',structureType:'Composite microstructure',phase:'alpha hcp + beta bcc',composition:'Ti–6Al–4V representative two-phase field',model:{kind:'twophase',phases:[{name:'α-Ti (HCP)',element:'Ti',lattice:[[2.935731,0,0],[-1.467866,2.542419,0],[0,0,4.640856]],basis:[[1/3,2/3,.25],[2/3,1/3,.75]]},{name:'β-Ti (BCC)',element:'Ti',lattice:[[2.654949,0,-.938666],[-1.327476,2.299254,-.938666],[0,0,2.815999]],basis:[[0,0,0]]}]},elements:['Ti','Al','V'],source:src('Materials Project mp-46 alpha-Ti and mp-73 beta-Ti',MP+'mp-46'),modellingNotes:'Phase lattices are sourced; grain morphology and alloy partitioning are representative, not an atom-exact Ti-6Al-4V cell.',limitations:['Phase fraction depends on thermomechanical history.']}),
 nitinol:crystal({representation:'crystal lattice',structureType:'B2 cubic',phase:'B2 austenite',composition:'equiatomic NiTi',lattice:{vectors:[[2.988066,0,0],[0,2.988066,0],[0,0,2.988066]],unit:'Å'},repeat:[2,2,2],atoms:[frac('Ni',[0,0,0],'corner Ni'),frac('Ti',[.5,.5,.5],'body-centre Ti')],source:src('Materials Project mp-571, B2 NiTi',MP+'mp-571'),modellingNotes:'B2 austenite only; B19-prime is not conflated with this phase.',limitations:['Transformation texture and off-stoichiometry are not represented.']}),
 steel:crystal({exact:false,representation:'crystal lattice',structureType:'FCC',phase:'gamma-Fe austenitic matrix',composition:'316L representative Fe–Cr–Ni–Mo solid solution',lattice:{vectors:[[2.238559,0,1.292433],[.746186,2.110534,1.292433],[0,0,2.584864]],unit:'Å'},repeat:[3,3,3],atoms:[frac('Fe',[0,0,0],'austenitic matrix')],model:{kind:'substitute',substitutions:[['Cr',5],['Ni',4],['Mo',1]]},elements:['Fe','Cr','Ni','Mo'],source:src('Materials Project mp-150 gamma-Fe matrix; ASTM A240 316L composition','https://www.astm.org/a0240_a0240m-24.html','sourced matrix plus representative composition model'),modellingNotes:'Substitution sites are deterministic visual representatives of a disordered solid solution.',limitations:['Not a special-quasirandom structure or grain-resolved alloy.']}),
 alli:representative({representation:'representative microstructure',structureType:'Composite microstructure',phase:'FCC Al matrix + T1 platelets',composition:'2195 Al–Cu–Li representative',model:{kind:'precipitate',matrix:'Al',lattice:[[2.473329,0,1.427977],[.824443,2.331877,1.427977],[0,0,2.855955]],precipitate:['Al','Cu','Li']},elements:['Al','Cu','Li'],source:src('Materials Project mp-134 FCC Al; Rioja & Liu, Metall. Mater. Trans. A 43 (2012)',MP+'mp-134'),modellingNotes:'Al matrix lattice is sourced; T1 platelet shape and displayed chemistry are representative at microstructural scale.',limitations:['No unique precipitate population exists.']}),
 cfrp:representative({representation:'representative microstructure',structureType:'Composite microstructure',phase:'0/90 carbon-fibre/epoxy laminate',composition:'carbon fibres + epoxy matrix',model:{kind:'fibres'},elements:['C'],phases:[{name:'Carbon fibre',color:'#39434f'},{name:'Epoxy matrix',color:'#b07962'}],source:src('Gay, Composite Materials: Design and Applications, 3rd ed. (2014)','https://doi.org/10.1201/b17106','composite morphology reference'),modellingNotes:'Fibre-scale cross-ply section; atomic lattice is inappropriate for a composite.',limitations:['Layup and fibre volume fraction are representative.']}),
 kevlar:representative({representation:'polymer chain',structureType:'Polymer repeat unit',phase:'aligned PPTA chains',composition:'[-CO-C6H4-CO-NH-C6H4-NH-]n',model:{kind:'polymer',sequence:['C','C','N','C','C','O'],chains:4,rings:true},elements:['C','N','O','H'],source:src('Northolt, Eur. Polym. J. 10, 799–804 (1974)','https://doi.org/10.1016/0014-3057(74)90110-7','fibre structure reference'),modellingNotes:'Identifiable repeat-unit chain packing; hydrogens are implicit in rendering.',limitations:['Radial pleating and disorder are simplified.']}),
 pla:representative({representation:'polymer chain',structureType:'Polymer repeat unit',phase:'semicrystalline PLLA',composition:'[-CH(CH3)-CO-O-]n',model:{kind:'polymer',sequence:['C','C','O','C','O'],chains:3,lamella:true},elements:['C','O','H'],source:src('Garlotta, J. Polym. Environ. 9, 63–84 (2001)','https://doi.org/10.1023/A:1020200822435','polymer review'),modellingNotes:'Repeat units span an ordered lamella and a disordered chain region.',limitations:['Crystallinity is processing-dependent.']}),
 peek:representative({representation:'polymer chain',structureType:'Polymer repeat unit',phase:'semicrystalline PEEK',composition:'[-C6H4-O-C6H4-O-C6H4-CO-]n',model:{kind:'polymer',sequence:['C','O','C','C','O'],chains:3,rings:true,lamella:true},elements:['C','O','H'],source:src('Kurtz, PEEK Biomaterials Handbook (2012)','https://doi.org/10.1016/C2010-0-66010-6','polymer reference'),modellingNotes:'Aromatic repeat-unit chain model with a labelled crystalline lamella.',limitations:['Hydrogens implicit; lamellar dimensions schematic.']}),
 silicone:representative({representation:'polymer chain',structureType:'Polymer repeat unit',phase:'crosslinked amorphous PDMS',composition:'[-Si(CH3)2-O-]n',model:{kind:'polymer',sequence:['Si','O'],chains:4,side:['C','C'],crosslinks:true},elements:['Si','O','C','H'],source:src('Mark, Polymer Data Handbook (1999)','https://doi.org/10.1093/oso/9780195107890.001.0001','polymer reference'),modellingNotes:'Si-O repeat units and selected crosslinks shown; hydrogens implicit.',limitations:['Crosslink chemistry and density vary.']}),
 hydrogel:representative({representation:'representative model',structureType:'Polymer repeat unit',phase:'water-swollen crosslinked network',composition:'representative polymer + H2O',model:{kind:'hydrogel'},elements:['C','O','H'],phases:[{name:'Polymer network',color:'#7e83c7'},{name:'Water',color:'#4aaed0'}],source:src('Wichterle & Lim, Nature 185, 117–118 (1960)','https://doi.org/10.1038/185117a0','hydrogel network reference'),modellingNotes:'Network/solvent mesoscale model; water points are phase markers rather than bonded atoms.',limitations:['Polymer identity and swelling ratio are formulation-specific.']}),
 cellulose:representative({representation:'polymer chain',structureType:'Polymer repeat unit',phase:'cellulose I-beta nanofibril',composition:'(C6H10O5)n',model:{kind:'polymer',sequence:['C','O','C','C','O','C'],chains:5,rings:true,lamella:true},elements:['C','O','H'],source:src('Nishiyama et al., J. Am. Chem. Soc. 124, 9074–9082 (2002)','https://doi.org/10.1021/ja0257319','crystallographic fibre reference'),modellingNotes:'Glucan repeat motifs are packed into a representative I-beta fibril; hydrogens implicit.',limitations:['Full hydrogen-bond geometry is not resolved.']}),
 mycelium:representative({representation:'representative microstructure',structureType:'Composite microstructure',phase:'dried mycelium composite',composition:'chitin-rich hyphae + particulate substrate',model:{kind:'mycelium'},phases:[{name:'Hyphae',color:'#9b7b50'},{name:'Substrate',color:'#5f4935'}],source:src('Jones et al., Materials & Design 187, 108397 (2020)','https://doi.org/10.1016/j.matdes.2019.108397','microstructure review'),modellingNotes:'Deterministic branching hyphal network at microstructural scale; no exact atomic structure is claimed.',limitations:['Species, substrate and growth conditions change morphology.']})
};

if(typeof module!=='undefined') module.exports={ELEMENTS,STRUCTURE_TYPES,STRUCTURE_DATA};
